### ISSUE TITLE
Работа с API Google Places

### ISSUE THREAD

**Issue by gazarovv** [gazarovv/travelerBot#6]
Наладить работу с апи

**Comment by gazarovv** [comment]
https://github.com/gazarovv/travelerBot/tree/API
Создал ветку

**Comment by aspekt112** [comment]
Добавлена работа с api-запросом на наличие рядом мест нужного типа.

**Comment by aspekt112** [comment]
API v2. Добавлен вывод мест в нерегулируемом радиусе(500м).
Добавлен token ArtNurBot

**Comment by aspekt112** [comment]
Внесены правки после показа бота.
